<?php

ini_set('newrelic.appname', 'GW2Spidy');

// autoload.php generated by Composer
if (!class_exists('Composer\\Autoload\\ClassLoader', false)) {
    require __DIR__ . '/vendor/composer' . '/ClassLoader.php';
}

$loader = new \Composer\Autoload\ClassLoader();
$composerDir = __DIR__ . '/vendor/composer';

$map = require $composerDir . '/autoload_namespaces.php';
foreach ($map as $namespace => $path) {
    $loader->add($namespace, $path);
}

$classMap = require $composerDir . '/autoload_classmap.php';
if ($classMap) {
    $loader->addClassMap($classMap);
}

$loader->add('GW2Spidy', __DIR__.'/src');
$loader->add('Predis',   __DIR__.'/vendor/nrk-predis/lib');

$loader->register();

// Include the main Propel script
require_once __DIR__ . '/vendor/propel/runtime/lib/Propel.php';

// Initialize Propel with the runtime configuration
Propel::init(__DIR__ . "/config/gw2spidy-conf.php");
