<?php

// autoload.php generated by Composer
if (!class_exists('Composer\\Autoload\\ClassLoader', false)) {
    require __DIR__ . '/vendor/composer' . '/ClassLoader.php';
}

$loader = new \Composer\Autoload\ClassLoader();
$composerDir = __DIR__ . '/vendor/composer';

$map = require $composerDir . '/autoload_namespaces.php';
foreach ($map as $namespace => $path) {
    $loader->add($namespace, $path);
}

$classMap = require $composerDir . '/autoload_classmap.php';
if ($classMap) {
    $loader->addClassMap($classMap);
}

$loader->add('GW2Spidy', __DIR__.'/src');
$loader->add('ShroudMagic', __DIR__.'/src');
$loader->add('SamuiraiMagic', __DIR__.'/src');
$loader->add('Predis',   __DIR__.'/vendor/nrk-predis/lib');
$loader->add('Igorw',    __DIR__.'/vendor/igorw/src');

$loader->register();

/**
 * @return \Igorw\Silex\Env
 */
function getAppEnv() {
    static $env = null;

    if (is_null($env)) {
        $env = new \Igorw\Silex\Env(__DIR__ . "/config/cnf");
    }

    return $env;
}

/**
 * @return \Igorw\Silex\Config
 */
function getAppConfig($key = null) {
    static $cnf = null;

    if (is_null($cnf)) {
        $cnf = new \Igorw\Silex\Config(getAppEnv());
    }

    if (!is_null($key)) {
        return $cnf->getConfig($key);
    }

    return $cnf;
}

// Include the main Propel script
require_once __DIR__ . '/vendor/propel/runtime/lib/Propel.php';

// Initialize Propel with the runtime configuration
$propelcnf = (array)getAppConfig('propel');
$propelcnf['classmap'] = include(__DIR__ . '/config/classmap-gw2spidy-conf.php');
Propel::setConfiguration($propelcnf);
Propel::initialize();

// set newrelic_background_job if on CLI and newrelic is enabled
if (function_exists('newrelic_background_job') && php_sapi_name() == 'cli') {
    newrelic_background_job(true);
}

require_once __DIR__ . '/vendor/simple_html_dom/simple_html_dom.php';



require_once __DIR__ .'/src/GW2Spidy/GW2API/API_Item.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Weapon.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Armor.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Bag.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Consumable.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Container.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/CraftingMaterial.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Gathering.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Gizmo.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/MiniPet.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Tool.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Trinket.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Trophy.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/UpgradeComponent.php';
require_once __DIR__ .'/src/GW2Spidy/GW2API/Weapon.php';