<?php
// This file generated by Propel 1.6.7-dev convert-conf target
return array (
  'GW2Spidy\\DB\\Item' => 'gw2spidy/Item.php',
  'GW2Spidy\\DB\\ItemPeer' => 'gw2spidy/ItemPeer.php',
  'GW2Spidy\\DB\\ItemQuery' => 'gw2spidy/ItemQuery.php',
  'GW2Spidy\\DB\\map\\ItemTableMap' => 'gw2spidy/map/ItemTableMap.php',
  'GW2Spidy\\DB\\om\\BaseItem' => 'gw2spidy/om/BaseItem.php',
  'GW2Spidy\\DB\\om\\BaseItemPeer' => 'gw2spidy/om/BaseItemPeer.php',
  'GW2Spidy\\DB\\om\\BaseItemQuery' => 'gw2spidy/om/BaseItemQuery.php',
  '\\GW2Spidy\\DB\\ItemType' => 'gw2spidy/ItemType.php',
  '\\GW2Spidy\\DB\\ItemTypePeer' => 'gw2spidy/ItemTypePeer.php',
  '\\GW2Spidy\\DB\\ItemTypeQuery' => 'gw2spidy/ItemTypeQuery.php',
  '\\GW2Spidy\\DB\\map\\ItemTypeTableMap' => 'gw2spidy/map/ItemTypeTableMap.php',
  '\\GW2Spidy\\DB\\om\\BaseItemType' => 'gw2spidy/om/BaseItemType.php',
  '\\GW2Spidy\\DB\\om\\BaseItemTypePeer' => 'gw2spidy/om/BaseItemTypePeer.php',
  '\\GW2Spidy\\DB\\om\\BaseItemTypeQuery' => 'gw2spidy/om/BaseItemTypeQuery.php',
);