<?php
// This file generated by Propel 1.6.7-dev convert-conf target
// from XML runtime conf file /work/gw2spider/config/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'gw2spidy' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=gw2spidy',
        'user' => 'gw2spidy',
        'password' => 'gw2spidy',
      ),
    ),
    'default' => 'gw2spidy',
  ),
  'log' => 
  array (
    'type' => 'file',
    'name' => '/var/log/propel/gw2spidy.log',
    'ident' => 'propel-gw2spidy',
    'level' => '7',
  ),
  'generator_version' => '1.6.7-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-gw2spidy-conf.php');
return $conf;
